### ISSUE TITLE
USER STORY: Contact Page Form

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/studio-booking-site#10]
As a **user** I can **send queries to the business** so that **I can find out more about them**.

# Acceptance Criteria:
- This page can be found from the menu and will include a contact form to contact the business.
- This form will include: users name (first & last), mobile #, email address, dropdown of class interested in (or *other option), text box to enter query (with placeholder text). 
- A submit button will be located below the form to allow the user to send the query.
- Confirmation of submission will appear in a pop up modal.

# Tasks:
- [x] Create Contact page accessible from the menu 
- [x] Create a contact form
- [x] Include fields for user's First Name, Last Name, Mobile Number, Email Address, Class interested in (dropdown), and Query section (text box).
- [x] Add a submit button to send query
- [x] Ensure validation for required fields
- [x] Implement a success message to confirm successful submission of query
- [x] Ensure that submitted queries are sent to admin dashboard
