### ISSUE TITLE
USER STORY: Admin -- Receive queries from Contact Form

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/studio-booking-site#11]
As a **site owner** I can **receive queries from users** so that **I can contact potential clients**.

# Acceptance Criteria:
- Queries submitted from the contact form should appear in the admin dashboard.
- Received information should include the following: users name (first & last), mobile #, email address, class interested in (or *other option), text input from user.

# Tasks:
- [x] Modify admin dashboard to view received queries
- [x] Ensure that the displayed information includes the user's Name, Phone Number (optional), Email Address, Class Interest (optional), and Query Text.
- [x] Verify that only authorized admin can view queries and details received
