### ISSUE TITLE
USER STORY: Class Booking for logged in users

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/studio-booking-site#12]
As a **user** I can **book a class** so that **I can attend a class that suits my schedule**.

# Acceptance Criteria:
- This page should be available in the menu. 
- This should only be accessible to logged in users. 
- Booking dropdown options should include: Class name, date & time 
- The user should be redirected to their profile page with the updated booking

# Tasks:
- [x] Add a link to booking page in the menu (ONLY accessible when a user is logged in)
- [x] Utilize Django AllAuth to check authentication and restrict access
- [x] Create a form on the booking page to allow users to select the class name, date, and time from dropdown options.
- [x] Redirect user to profile page once booking is confirmed
- [x] Ensure new booking is reflected on user's profile page
- [x] Store the booking details and update the admin dashboard
