### ISSUE TITLE
USER STORY: Confirmation of class booking

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/studio-booking-site#13]
As a **user** I can **receive confirmation of a booking** so that **I know it was successfully booked**.

# Acceptance Criteria:
- Confirmation of the booking will appear in a modal pop-up with booking confirmation details of class.
- New booking should be reflected in the user's profile page.
- New booking should be reflected on the admin dashboard.

# Tasks:
- [x] Implement success message with confirmation of class booking
- [x] Update the user's profile page to reflect the new booking
- [x] Ensure new bookings are reflected on the admin dashboard
