### ISSUE TITLE
USER STORY: Admin -- Send alerts to users

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/studio-booking-site#15]
As a **site owner** I can **view client contact information** so that **I can send alerts of any changes made within the business**.

# Acceptance Criteria:
- The admin dashboard should include an email form to send updates to clients
- The form should include fields for: Send to (user's email), From (admin email), Text box for admin to add details of message
- The admin should be able to send an email to all registered users

# Tasks:
- [ ] Implement an email form section in the admin dashboard 
- [ ] Configure the backend email settings to enable sending emails
- [ ] Provide options for selecting recipients from the list of registered users
- [ ] Allow admin to customize the content of the email
