### ISSUE TITLE
USER STORY: Admin -- Send class reminder emails

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/studio-booking-site#16]
As a **site owner** I can **send email alerts to clients** so that **clients are reminded of a booked class**. 

# Acceptance Criteria:
- The admin dashboard should include an email form with class booking details.
- The form should include fields for: User, Class booked, Date of Class, Time of Class.
- Emails should automatically be sent to users within a specified timeframe before a class (ie. 1-2 days before a booked class)

# Tasks:
- [ ] Implement an email form section in the admin dashboard
- [ ] Include fields for the user, class booked, date of class, time of class, and any additional message details
- [ ] Configure backend email settings
- [ ] Relay information of booked classes
- [ ] Allow admin to customize the content of the email
