### ISSUE TITLE
USER STORY: Weekly Class Schedule & Class Descriptions

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/studio-booking-site#4]
As a **user** I can **see the weekly class schedule** so that **I can find a class that suits my schedule**.

# Acceptance Criteria:
- This page can be found from the menu. 
- The class schedule should appear on it's own page for better UX.
- The class schedule page will also include descriptions of each class provided below the schedule.

# Tasks:
- [x] Create static file in main app to create page
- [x] Create URL path to navigate to page from the menu
- [x] Apply studio class schedule and descriptions to page (HTML & CSS)
