### ISSUE TITLE
USER STORY: Gallery page

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/studio-booking-site#5]
As a **user** I can **see photos** so that **I can have a better idea of the class atmosphere**.

# Acceptance Criteria:
- This gallery page can be found from the menu.
- The photos should be responsive to the size of screen.
- The photos should easily depict the atmosphere of the studio and what a user can expect from a class.

# Tasks:
- [ ] Gather photos to use in gallery page
- [ ] Ensure photos are compressed and in the correct format
- [ ] Use Bootstrap to style an appealing gallery page
- [ ] Create URL for gallery page to be found in menu
- [ ] Create static page in main app for gallery images
