### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/studio-booking-site#6]
As a **first time user** I want to **be able to register for an account** so that **I can access the studio booking platform**.

# Acceptance Criteria:
- The register button should be visible in the menu if a user is not logged in.
- Registration details should require: First name, Last name, Username, Password, Email Address, Phone number
- Confirmation of registration will appear in a pop up modal.

# Tasks:
- [x] Display a "Register" button in the menu - only if a user is not logged in
- [x] Ensure user's menu options change after being logged in
- [x] Ensure that user registrations are recorded and displayed on the admin dashboard
