### ISSUE TITLE
USER STORY: User Login to View Bookings

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/studio-booking-site#7]
As a **returning visitor** I can **login to my account** so that **I can manage my bookings**.

# Acceptance Criteria:
- A login button should be easily accessible to the user within the menu bar.
- When clicked, the user will be given the option to login with existing username and password.
- The user will be directed to their profile page & be able to view the classes they have booked. 
- If no classes are booked yet, a message to user will appear in a modal to book first class.

# Tasks:
- [x] Display a "Login" button in the menu, only if a user is not logged in.
- [x] Create a login form with fields for Username and Password.
- [x] Implement Django AllAuth to implement user authentication & restrict access
- [x] Create a profile page that shows the user's booked classes
- [x] Add a button to allow the user to book a class
