### ISSUE TITLE
USER STORY: User Login to Cancel Bookings

### ISSUE THREAD

**Issue by morganoleary** [morganoleary/studio-booking-site#8]
As a **returning visitor** I can **login to my account** so that **I can cancel a booked class**.

# Acceptance Criteria:
- The user will be directed to the home page, where they can access the member profile page from the menu & be able to select a booked class.
- Each booked class will have an option to cancel the class (Cancel button).
- Cancellation of a class should update the admin dashboard accordingly.
- Confirmation of cancellation should appear.

# Tasks:
- [x] User login will redirect user to the home page
- [x] Add "Cancel" button for each booked class
- [x] Ensure booking is cancelled & updated on admin dashboard
- [x] Implement a message of cancellation confirmation
